import {
  faEye as fasEye,
  faStar as fasStar,
  faHeart as fasHeart,
  faEllipsisH,
  faShoppingBasket,
  faUser as fasUser,
  faSquare as fasSquare,
  faRedoAlt,
  faInfoCircle as fasInfoCircle,
  faThLarge,
  faComments as fasComments,
  faPen,
  faPaperPlane,
  faBan,
  faRocket,
  faDollarSign,
  faPlus,
  faBoxOpen,
  faGlobeAsia,
  faUniversity,
  faHashtag,
  faBullhorn,
  faBriefcase,
  faEnvelopeOpen,
  faSortAmountUp,
  faCartArrowDown,
} from "@fortawesome/free-solid-svg-icons";

import {
  faEye,
  faStar,
  faHeart,
  faUser,
  faSquare,
  faComments,
  faBell,
  faDotCircle,
  faCheckCircle,
  faTimesCircle,
  faFlag,
  faClone,
  faStickyNote,
  faImage,
  faQuestionCircle,
} from "@fortawesome/free-regular-svg-icons";

export default [
  fasEye,
  faEye,
  fasStar,
  faStar,
  fasHeart,
  faHeart,
  faEllipsisH,
  faShoppingBasket,
  fasUser,
  faUser,
  faSquare,
  fasSquare,
  faRedoAlt,
  faThLarge,
  fasInfoCircle,
  faComments,
  fasComments,
  faBell,
  faPen,
  faPaperPlane,
  faBan,
  faRocket,
  faDollarSign,
  faPlus,
  faBoxOpen,
  faGlobeAsia,
  faDotCircle,
  faCheckCircle,
  faTimesCircle,
  faUniversity,
  faHashtag,
  faBullhorn,
  faFlag,
  faBriefcase,
  faClone,
  faStickyNote,
  faImage,
  faEnvelopeOpen,
  faSortAmountUp,
  faCartArrowDown,
  faQuestionCircle,
];
