import {
  faEye as fasEye,
  faStar as fasStar,
  faHeart as fasHeart,
  faEllipsisH,
  faShoppingBasket,
  faUser as fasUser,
  faSquare as fasSquare,
  faRedoAlt,
  faInfoCircle as fasInfoCircle,
  faThLarge,
  faComments as fasComments,
  faPen,
  faPaperPlane,
  faBan,
  faRocket,
  faDollarSign,
} from "@fortawesome/free-solid-svg-icons";

import {
  faEye,
  faStar,
  faHeart,
  faUser,
  faSquare,
  faComments,
  faBell,
} from "@fortawesome/free-regular-svg-icons";

export default [
  fasEye,
  faEye,
  fasStar,
  faStar,
  fasHeart,
  faHeart,
  faEllipsisH,
  faShoppingBasket,
  fasUser,
  faUser,
  faSquare,
  fasSquare,
  faRedoAlt,
  faThLarge,
  fasInfoCircle,
  faComments,
  fasComments,
  faBell,
  faPen,
  faPaperPlane,
  faBan,
  faRocket,
  faDollarSign,
];
