module.exports = {
  OPEN_NOTIFICATION_SIDEBAR: "OPEN_NOTIFICATION_SIDEBAR",
  OPEN_SEND_MESSAGE_MODAL: "OPEN_SEND_MESSAGE_MODAL",
  OPEN_VIEW_EDUCATION_HISTORY_MODAL: "OPEN_VIEW_EDUCATION_HISTORY_MODAL",
};
